spring:
 datasource:
    username: system
    url: jdbc:oracle:thin:@10.120.93.4:1521:free
    driverClassName: oracle.jdbc.driver.OracleDriver
    password: root
 jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update

server:
        port: 7070
application:
          name: loan-app-system