server:
  port: 8081

spring:
  ldap:
    embedded:
      base-dn: dc=springframework,dc=org
      ldif: classpath:test-server.ldif
      port: 8389

  security:
    ldap:
      urls: ldap://localhost:8389/
      base: dc=springframework,dc=org
      user-dn-pattern: uid={0},ou=people
